services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: db
      POSTGRES_PASSWORD: db
    volumes:
      - db1:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      update_config:
        order: start-first
      restart_policy:
        condition: any
volumes:
  db1:
networks:
  default:
    driver: overlay
    attachable: true
